//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eteklifn_netEntities : DbContext
    {
        public eteklifn_netEntities()
            : base("name=eteklifn_netEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLLISTEPARAM> TBLLISTEPARAM { get; set; }
        public virtual DbSet<TBLTEKLIF> TBLTEKLIF { get; set; }
        public virtual DbSet<TBLTEKLIFHAR> TBLTEKLIFHAR { get; set; }
        public virtual DbSet<TBLTEKLIFNO> TBLTEKLIFNO { get; set; }
        public virtual DbSet<TBLSIRKETLER> TBLSIRKETLER { get; set; }
        public virtual DbSet<TBLCASABIT> TBLCASABIT { get; set; }
        public virtual DbSet<TBLKULLANP> TBLKULLANP { get; set; }
        public virtual DbSet<TBLSTSABIT> TBLSTSABIT { get; set; }
    }
}
