//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLCASABIT
    {
        public int CARI_ID { get; set; }
        public int SIRKET_ID { get; set; }
        public string CARI_ISIM { get; set; }
        public string CARI_KODU { get; set; }
        public string CARI_TEL { get; set; }
        public string CARI_GSM { get; set; }
        public string CARI_IL { get; set; }
        public string CARI_ILCE { get; set; }
        public string CARI_ADRES { get; set; }
        public string GRUP_KODU { get; set; }
        public string RAPOR_KODU1 { get; set; }
        public string RAPOR_KODU2 { get; set; }
        public string RAPOR_KODU3 { get; set; }
        public string RAPOR_KODU4 { get; set; }
        public string RAPOR_KODU5 { get; set; }
        public string TCKIMLIKNO { get; set; }
        public string VERGI_DAIRESI { get; set; }
        public string VERGI_NUMARASI { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }

        [Display(Name = "Ýskonto Oraný")]
        public Nullable<double> ISKONTO_ORANI { get; set; }

        public string KAYITTARIHI { get; set; }
        public string KAYITYAPANKULL { get; set; }
        public string DUZELTMETARIHI { get; set; }
        public string DUZELTMEYAPANKULL { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string S_YEDEK5 { get; set; }
        public Nullable<double> F_YEDEK1 { get; set; }
        public Nullable<double> F_YEDEK2 { get; set; }
        public Nullable<double> F_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
    }
}
