//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANP
    {
        public int ID { get; set; }
        public int SIRKET_ID { get; set; }
        public string KULL_KODU { get; set; }
        public string KULL_ADI { get; set; }
        public string SIFRE { get; set; }
        public string YETKI { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
        public string TEKLIF_SERI { get; set; }
        public Nullable<bool> ISVALID { get; set; }
        public Nullable<System.Guid> AKTIVASYON_LINK { get; set; }
        public string SIFRESIFIRLAMA_CODE { get; set; }
        public string KAYITTARIHI { get; set; }
        public string KAYITYAPANKULL { get; set; }
        public string DUZELTMETARIHI { get; set; }
        public string DUZELTMEYAPANKULL { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string S_YEDEK5 { get; set; }
        public Nullable<double> F_YEDEK1 { get; set; }
        public Nullable<double> F_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
    }
}
