//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLSTSABIT
    {
        public int STOK_ID { get; set; }
        public int SIRKET_ID { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string ING_ADI { get; set; }
        public string GRUP_KODU { get; set; }
        public string KOD_1 { get; set; }
        public string KOD_2 { get; set; }
        public string KOD_3 { get; set; }
        public string KOD_4 { get; set; }
        public string KOD_5 { get; set; }

        [Display(Name = "Satýþ Fiyatý1")]
        public Nullable<double> SATIS_FIAT1 { get; set; }

        [Display(Name = "Satýþ Fiyatý2")]
        public Nullable<double> SATIS_FIAT2 { get; set; }

        [Display(Name = "Satýþ Fiyatý3")]
        public Nullable<double> SATIS_FIAT3 { get; set; }

        [Display(Name = "Satýþ Fiyatý4")]
        public Nullable<double> SATIS_FIAT4 { get; set; }

        [Display(Name = "Alýþ Fiyatý1")]
        public Nullable<double> ALIS_FIAT1 { get; set; }

        [Display(Name = "Alýþ Fiyatý2")]
        public Nullable<double> ALIS_FIAT2 { get; set; }

        [Display(Name = "Alýþ Fiyatý3")]
        public Nullable<double> ALIS_FIAT3 { get; set; }

        [Display(Name = "Alýþ Fiyatý4")]
        public Nullable<double> ALIS_FIAT4 { get; set; }

        [Display(Name = "Satýþ Fiyatý")]
        public Nullable<int> SAT_DOV_TIP { get; set; }

        [Display(Name = "Döviz Satýþ Fiyatý")]
        public Nullable<double> DOV_SATIS_FIAT { get; set; }
        public Nullable<bool> TEKLIFMIKTAR { get; set; }
        public string OLCU_BR1 { get; set; }

        [Display(Name = "Kdv Oraný")]
        public Nullable<double> KDV_ORANI { get; set; }
        public string BARKOD1 { get; set; }
        public string BARKOD2 { get; set; }
        public string BARKOD3 { get; set; }
        public Nullable<bool> PASIF { get; set; }
        public string KAYITTARIHI { get; set; }
        public string KAYITYAPANKULL { get; set; }
        public string DUZELTMETARIHI { get; set; }
        public string DUZELTMEYAPANKULL { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string S_YEDEK5 { get; set; }
        public Nullable<double> F_YEDEK1 { get; set; }
        public Nullable<double> F_YEDEK2 { get; set; }
        public Nullable<double> F_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
    }
}
