//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIRKETLER
    {
        public int SIRKET_ID { get; set; }
        public string SIRKET_UNVANI { get; set; }
        public string SIRKET_YETKILI { get; set; }
        public string SIRKET_ADRES { get; set; }
        public string SIRKET_IL { get; set; }
        public string SIRKET_ILCE { get; set; }
        public string SIRKET_VERGIDAIRESI { get; set; }
        public string SIRKET_VERGINUMARASI { get; set; }
        public string SIRKET_TELEFON { get; set; }
        public string SIRKET_GSM { get; set; }
        public string SIRKET_FAX { get; set; }
        public string SIRKET_MAIL { get; set; }
        public string SIRKET_POSTAKODU { get; set; }
        public string KEY { get; set; }
        public Nullable<System.DateTime> SIRKET_KAYITTARIHI { get; set; }
        public string KAYITYAPANKULL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string DUZELTMEYAPANKULL { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string S_YEDEK5 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<double> F_YEDEK1 { get; set; }
        public Nullable<double> F_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
    }
}
