//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTEKLIF
    {
        public int SIRKET_ID { get; set; }
        public string FISNO { get; set; }
        public int REVNO { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIK1 { get; set; }
        public string ACIK2 { get; set; }
        public string ACIK3 { get; set; }
        public Nullable<double> GEN_ISK1O { get; set; }
        public Nullable<double> GEN_ISK2O { get; set; }
        public Nullable<double> GEN_ISK3O { get; set; }
        public Nullable<double> GEN_ISK1T { get; set; }
        public Nullable<double> GEN_ISK2T { get; set; }
        public Nullable<double> GEN_ISK3T { get; set; }
        public Nullable<double> BRUTTUTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> GENELTOPLAM { get; set; }
        public Nullable<double> SATIR_ISKT { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string KAYITYAPANKULL { get; set; }
        public Nullable<System.DateTime> DUZELTMETARIHI { get; set; }
        public string DUZELTMEYAPANKULL { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public string S_YEDEK3 { get; set; }
        public string S_YEDEK4 { get; set; }
        public string S_YEDEK5 { get; set; }
        public Nullable<double> F_YEDEK1 { get; set; }
        public Nullable<double> F_YEDEK2 { get; set; }
        public Nullable<double> F_YEDEK3 { get; set; }
        public Nullable<System.DateTime> D_YEDEK1 { get; set; }
        public Nullable<System.DateTime> D_YEDEK2 { get; set; }
        public Nullable<System.DateTime> D_YEDEK3 { get; set; }
        public Nullable<int> I_YEDEK1 { get; set; }
        public Nullable<int> I_YEDEK2 { get; set; }
        public Nullable<int> I_YEDEK3 { get; set; }
    }
}
