//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTEKLIFHAR
    {
        public Nullable<int> SIRKET_ID { get; set; }
        public string FISNO { get; set; }
        public Nullable<int> REVNO { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string GCKOD { get; set; }
        public string STOK_KODU { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> NET_FIYAT { get; set; }
        public Nullable<double> BRUT_FIYAT { get; set; }
        public Nullable<int> DEPO_KODU { get; set; }
        public Nullable<double> KDV { get; set; }
        public string ACIK1 { get; set; }
        public string ACIK2 { get; set; }
        public string ACIK3 { get; set; }
        public Nullable<double> SAT_ISK1 { get; set; }
        public Nullable<double> SAT_ISK2 { get; set; }
        public Nullable<double> SAT_ISK3 { get; set; }
        public string EKALAN { get; set; }
        public string EKALAN1 { get; set; }
        public int INCKEYNO { get; set; }
    }
}
